### ISSUE TITLE
Activity Registration: Implement activity details components

### ISSUE THREAD

**Issue by u12206050** [bcc-code/bcc-vue-components#15]
Implement components from the Activity Registration design that are reusable in the component library.

- [x] Capacity indicator => #19
- [x] Badge => https://github.com/bcc-code/bcc-vue-components/pull/16
- [ ] #20
- [ ] #21
- [ ] #22

Other components are implemented in the project itself.

Not a component for now:
- Drawer // https://vant-contrib.gitee.io/vant/#/en-US/popup https://headlessui.com/vue/dialog

**Comment by laurensgroeneveld** [comment]
Closing this as all remaining tasks have been split off to separate issues.
