### ISSUE TITLE
Slow unit-testing on the capacity indicator

### ISSUE THREAD

**Issue by jasverix** [bcc-code/bcc-vue-components#56]
It has this animation using 1 sec, so the unit-tests all have to wait for an extended amount of time to wait for the animation.

My suggestion is to remove the animation in the tests, and also have the possibility to not animate at all as a prop.

**Comment by u12206050** [comment]
Any suggestions as to how we can unit test animations?

**Comment by jasverix** [comment]
> Any suggestions as to how we can unit test animations?

Right now, not without having to wait. The problem was that it took too much time. So maybe befine a seperate test scope or something?

The first test did work, so it is most certainly possible to test.
